services:
  php-apache:
    build: .
    container_name: laravel-app
    volumes:
      - ./app/mylaravelapp:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql
    command: > 
          sh -c "composer install &&
          php artisan migrate"
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"  # NOTE: external:internal
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
